name: Build and Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version number"
        type: string
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      pages: read
      deployments: read
    env:
      releaseVersion: ${{ inputs.releaseVersion }}
      workingDirectory: ${{github.workspace}}/vendordep
    steps:
      - run: git config --global user.name "thenetworkgrinch" && git config --global user.email "thenetworkgrinch@noreply.users.github.com"
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - run: chmod +x gradlew
        working-directory: ${{ env.workingDirectory }}
      - name: Install roboRio toolchain
        run: ./gradlew installRoboRioToolchain
        working-directory: ${{ env.workingDirectory }}
      - name: Build vendordep
        run: ./gradlew build
        working-directory: ${{ env.workingDirectory }}
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ${{ env.workingDirectory }}/build/maven/
      - name: Publish vendordep
        run: ./gradlew publish
        working-directory: ${{ env.workingDirectory }}
      - name: Create new vendor JSON
        run: cp ${{ env.workingDirectory }}/build/maven/yams.json ${{ env.workingDirectory }}/build/maven/yams-${{inputs.releaseVersion}}.json
      - name: Create Vendor JSON Repo PR
        uses: wpilibsuite/vendor-json-repo/.github/actions/add_vendordep@main
        with:
          repo: Yet-Another-Software-Suite/vendor-json-repo
          token: ${{ secrets.PUBLISH_VENDOR_JSON_TOKEN }}
          vendordep_file: ${{ env.workingDirectory }}/build/maven/yams-${{inputs.releaseVersion}}.json
          pr_title: "Automatically add YAMS version ${{inputs.releaseVersion}}"
          pr_branch: "publish_yams_${{inputs.releaseVersion}}"
        continue-on-error: true
      - name: Output Pages Tree
        run: find ${{ env.workingDirectory }}/build/maven/ -type f
      - name: Upload pages
        run: git add . && git commit -m "Automatically add YAMS version ${{inputs.releaseVersion}}" && git push
        working-directory: ${{ env.workingDirectory }}/build/maven/
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Upload vendordep json, maven repository, and javadocs
        uses: actions/upload-pages-artifact@v4
        with:
          name: 'github-pages'
          retention-days: '90'
          path: ${{ env.workingDirectory }}/build/maven/

  deploy:
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
